// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/bobyindra/configs-management-service/module/configuration/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigsManagementUsecase is a mock of ConfigsManagementUsecase interface.
type MockConfigsManagementUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockConfigsManagementUsecaseMockRecorder
}

// MockConfigsManagementUsecaseMockRecorder is the mock recorder for MockConfigsManagementUsecase.
type MockConfigsManagementUsecaseMockRecorder struct {
	mock *MockConfigsManagementUsecase
}

// NewMockConfigsManagementUsecase creates a new mock instance.
func NewMockConfigsManagementUsecase(ctrl *gomock.Controller) *MockConfigsManagementUsecase {
	mock := &MockConfigsManagementUsecase{ctrl: ctrl}
	mock.recorder = &MockConfigsManagementUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigsManagementUsecase) EXPECT() *MockConfigsManagementUsecaseMockRecorder {
	return m.recorder
}

// CreateConfig mocks base method.
func (m *MockConfigsManagementUsecase) CreateConfig(ctx context.Context, params *entity.Config) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", ctx, params)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConfig indicates an expected call of CreateConfig.
func (mr *MockConfigsManagementUsecaseMockRecorder) CreateConfig(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockConfigsManagementUsecase)(nil).CreateConfig), ctx, params)
}

// GetConfigByConfigName mocks base method.
func (m *MockConfigsManagementUsecase) GetConfigByConfigName(ctx context.Context, params *entity.GetConfigRequest) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByConfigName", ctx, params)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByConfigName indicates an expected call of GetConfigByConfigName.
func (mr *MockConfigsManagementUsecaseMockRecorder) GetConfigByConfigName(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByConfigName", reflect.TypeOf((*MockConfigsManagementUsecase)(nil).GetConfigByConfigName), ctx, params)
}

// GetListVersionsByConfigName mocks base method.
func (m *MockConfigsManagementUsecase) GetListVersionsByConfigName(ctx context.Context, params *entity.GetListConfigVersionsRequest) ([]*entity.ConfigResponse, *entity.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListVersionsByConfigName", ctx, params)
	ret0, _ := ret[0].([]*entity.ConfigResponse)
	ret1, _ := ret[1].(*entity.PaginationResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListVersionsByConfigName indicates an expected call of GetListVersionsByConfigName.
func (mr *MockConfigsManagementUsecaseMockRecorder) GetListVersionsByConfigName(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListVersionsByConfigName", reflect.TypeOf((*MockConfigsManagementUsecase)(nil).GetListVersionsByConfigName), ctx, params)
}

// RollbackConfigVersionByConfigName mocks base method.
func (m *MockConfigsManagementUsecase) RollbackConfigVersionByConfigName(ctx context.Context, params *entity.Config) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackConfigVersionByConfigName", ctx, params)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackConfigVersionByConfigName indicates an expected call of RollbackConfigVersionByConfigName.
func (mr *MockConfigsManagementUsecaseMockRecorder) RollbackConfigVersionByConfigName(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackConfigVersionByConfigName", reflect.TypeOf((*MockConfigsManagementUsecase)(nil).RollbackConfigVersionByConfigName), ctx, params)
}

// UpdateConfigByConfigName mocks base method.
func (m *MockConfigsManagementUsecase) UpdateConfigByConfigName(ctx context.Context, params *entity.Config) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigByConfigName", ctx, params)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfigByConfigName indicates an expected call of UpdateConfigByConfigName.
func (mr *MockConfigsManagementUsecaseMockRecorder) UpdateConfigByConfigName(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigByConfigName", reflect.TypeOf((*MockConfigsManagementUsecase)(nil).UpdateConfigByConfigName), ctx, params)
}

// MockSessionUsecase is a mock of SessionUsecase interface.
type MockSessionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSessionUsecaseMockRecorder
}

// MockSessionUsecaseMockRecorder is the mock recorder for MockSessionUsecase.
type MockSessionUsecaseMockRecorder struct {
	mock *MockSessionUsecase
}

// NewMockSessionUsecase creates a new mock instance.
func NewMockSessionUsecase(ctrl *gomock.Controller) *MockSessionUsecase {
	mock := &MockSessionUsecase{ctrl: ctrl}
	mock.recorder = &MockSessionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionUsecase) EXPECT() *MockSessionUsecaseMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockSessionUsecase) Login(ctx context.Context, param *entity.LoginRequest) (*entity.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, param)
	ret0, _ := ret[0].(*entity.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockSessionUsecaseMockRecorder) Login(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockSessionUsecase)(nil).Login), ctx, param)
}
