// Code generated by MockGen. DO NOT EDIT.
// Source: schema_registry.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSchemaRegistry is a mock of SchemaRegistry interface.
type MockSchemaRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockSchemaRegistryMockRecorder
}

// MockSchemaRegistryMockRecorder is the mock recorder for MockSchemaRegistry.
type MockSchemaRegistryMockRecorder struct {
	mock *MockSchemaRegistry
}

// NewMockSchemaRegistry creates a new mock instance.
func NewMockSchemaRegistry(ctrl *gomock.Controller) *MockSchemaRegistry {
	mock := &MockSchemaRegistry{ctrl: ctrl}
	mock.recorder = &MockSchemaRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchemaRegistry) EXPECT() *MockSchemaRegistryMockRecorder {
	return m.recorder
}

// GetSchemaByConfigName mocks base method.
func (m *MockSchemaRegistry) GetSchemaByConfigName(configName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchemaByConfigName", configName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchemaByConfigName indicates an expected call of GetSchemaByConfigName.
func (mr *MockSchemaRegistryMockRecorder) GetSchemaByConfigName(configName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchemaByConfigName", reflect.TypeOf((*MockSchemaRegistry)(nil).GetSchemaByConfigName), configName)
}
