// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/bobyindra/configs-management-service/module/configuration/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigsManagementRepository is a mock of ConfigsManagementRepository interface.
type MockConfigsManagementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigsManagementRepositoryMockRecorder
}

// MockConfigsManagementRepositoryMockRecorder is the mock recorder for MockConfigsManagementRepository.
type MockConfigsManagementRepositoryMockRecorder struct {
	mock *MockConfigsManagementRepository
}

// NewMockConfigsManagementRepository creates a new mock instance.
func NewMockConfigsManagementRepository(ctrl *gomock.Controller) *MockConfigsManagementRepository {
	mock := &MockConfigsManagementRepository{ctrl: ctrl}
	mock.recorder = &MockConfigsManagementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigsManagementRepository) EXPECT() *MockConfigsManagementRepositoryMockRecorder {
	return m.recorder
}

// CreateConfig mocks base method.
func (m *MockConfigsManagementRepository) CreateConfig(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfig indicates an expected call of CreateConfig.
func (mr *MockConfigsManagementRepositoryMockRecorder) CreateConfig(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockConfigsManagementRepository)(nil).CreateConfig), ctx, obj)
}

// CreateConfigCache mocks base method.
func (m *MockConfigsManagementRepository) CreateConfigCache(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfigCache", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfigCache indicates an expected call of CreateConfigCache.
func (mr *MockConfigsManagementRepositoryMockRecorder) CreateConfigCache(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigCache", reflect.TypeOf((*MockConfigsManagementRepository)(nil).CreateConfigCache), ctx, obj)
}

// DeleteConfigCache mocks base method.
func (m *MockConfigsManagementRepository) DeleteConfigCache(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigCache", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigCache indicates an expected call of DeleteConfigCache.
func (mr *MockConfigsManagementRepositoryMockRecorder) DeleteConfigCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigCache", reflect.TypeOf((*MockConfigsManagementRepository)(nil).DeleteConfigCache), ctx, key)
}

// GetConfigByConfigName mocks base method.
func (m *MockConfigsManagementRepository) GetConfigByConfigName(ctx context.Context, obj *entity.GetConfigRequest) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByConfigName", ctx, obj)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByConfigName indicates an expected call of GetConfigByConfigName.
func (mr *MockConfigsManagementRepositoryMockRecorder) GetConfigByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByConfigName", reflect.TypeOf((*MockConfigsManagementRepository)(nil).GetConfigByConfigName), ctx, obj)
}

// GetConfigCache mocks base method.
func (m *MockConfigsManagementRepository) GetConfigCache(ctx context.Context, key string) (*entity.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigCache", ctx, key)
	ret0, _ := ret[0].(*entity.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigCache indicates an expected call of GetConfigCache.
func (mr *MockConfigsManagementRepositoryMockRecorder) GetConfigCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigCache", reflect.TypeOf((*MockConfigsManagementRepository)(nil).GetConfigCache), ctx, key)
}

// GetListVersionsByConfigName mocks base method.
func (m *MockConfigsManagementRepository) GetListVersionsByConfigName(ctx context.Context, obj *entity.GetListConfigVersionsRequest) ([]*entity.ConfigResponse, *entity.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListVersionsByConfigName", ctx, obj)
	ret0, _ := ret[0].([]*entity.ConfigResponse)
	ret1, _ := ret[1].(*entity.PaginationResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListVersionsByConfigName indicates an expected call of GetListVersionsByConfigName.
func (mr *MockConfigsManagementRepositoryMockRecorder) GetListVersionsByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListVersionsByConfigName", reflect.TypeOf((*MockConfigsManagementRepository)(nil).GetListVersionsByConfigName), ctx, obj)
}

// RollbackConfigVersionByConfigName mocks base method.
func (m *MockConfigsManagementRepository) RollbackConfigVersionByConfigName(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackConfigVersionByConfigName", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackConfigVersionByConfigName indicates an expected call of RollbackConfigVersionByConfigName.
func (mr *MockConfigsManagementRepositoryMockRecorder) RollbackConfigVersionByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackConfigVersionByConfigName", reflect.TypeOf((*MockConfigsManagementRepository)(nil).RollbackConfigVersionByConfigName), ctx, obj)
}

// UpdateConfigByConfigName mocks base method.
func (m *MockConfigsManagementRepository) UpdateConfigByConfigName(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigByConfigName", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigByConfigName indicates an expected call of UpdateConfigByConfigName.
func (mr *MockConfigsManagementRepositoryMockRecorder) UpdateConfigByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigByConfigName", reflect.TypeOf((*MockConfigsManagementRepository)(nil).UpdateConfigByConfigName), ctx, obj)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}
