// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/bobyindra/configs-management-service/module/configuration/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockConfigsManagementDBRepository is a mock of ConfigsManagementDBRepository interface.
type MockConfigsManagementDBRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigsManagementDBRepositoryMockRecorder
}

// MockConfigsManagementDBRepositoryMockRecorder is the mock recorder for MockConfigsManagementDBRepository.
type MockConfigsManagementDBRepositoryMockRecorder struct {
	mock *MockConfigsManagementDBRepository
}

// NewMockConfigsManagementDBRepository creates a new mock instance.
func NewMockConfigsManagementDBRepository(ctrl *gomock.Controller) *MockConfigsManagementDBRepository {
	mock := &MockConfigsManagementDBRepository{ctrl: ctrl}
	mock.recorder = &MockConfigsManagementDBRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigsManagementDBRepository) EXPECT() *MockConfigsManagementDBRepositoryMockRecorder {
	return m.recorder
}

// CreateConfig mocks base method.
func (m *MockConfigsManagementDBRepository) CreateConfig(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfig", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfig indicates an expected call of CreateConfig.
func (mr *MockConfigsManagementDBRepositoryMockRecorder) CreateConfig(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfig", reflect.TypeOf((*MockConfigsManagementDBRepository)(nil).CreateConfig), ctx, obj)
}

// GetConfigByConfigName mocks base method.
func (m *MockConfigsManagementDBRepository) GetConfigByConfigName(ctx context.Context, obj *entity.GetConfigRequest) (*entity.ConfigResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigByConfigName", ctx, obj)
	ret0, _ := ret[0].(*entity.ConfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigByConfigName indicates an expected call of GetConfigByConfigName.
func (mr *MockConfigsManagementDBRepositoryMockRecorder) GetConfigByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigByConfigName", reflect.TypeOf((*MockConfigsManagementDBRepository)(nil).GetConfigByConfigName), ctx, obj)
}

// GetListVersionsByConfigName mocks base method.
func (m *MockConfigsManagementDBRepository) GetListVersionsByConfigName(ctx context.Context, obj *entity.GetListConfigVersionsRequest) ([]*entity.ConfigResponse, *entity.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListVersionsByConfigName", ctx, obj)
	ret0, _ := ret[0].([]*entity.ConfigResponse)
	ret1, _ := ret[1].(*entity.PaginationResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListVersionsByConfigName indicates an expected call of GetListVersionsByConfigName.
func (mr *MockConfigsManagementDBRepositoryMockRecorder) GetListVersionsByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListVersionsByConfigName", reflect.TypeOf((*MockConfigsManagementDBRepository)(nil).GetListVersionsByConfigName), ctx, obj)
}

// RollbackConfigVersionByConfigName mocks base method.
func (m *MockConfigsManagementDBRepository) RollbackConfigVersionByConfigName(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackConfigVersionByConfigName", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackConfigVersionByConfigName indicates an expected call of RollbackConfigVersionByConfigName.
func (mr *MockConfigsManagementDBRepositoryMockRecorder) RollbackConfigVersionByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackConfigVersionByConfigName", reflect.TypeOf((*MockConfigsManagementDBRepository)(nil).RollbackConfigVersionByConfigName), ctx, obj)
}

// UpdateConfigByConfigName mocks base method.
func (m *MockConfigsManagementDBRepository) UpdateConfigByConfigName(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfigByConfigName", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfigByConfigName indicates an expected call of UpdateConfigByConfigName.
func (mr *MockConfigsManagementDBRepositoryMockRecorder) UpdateConfigByConfigName(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfigByConfigName", reflect.TypeOf((*MockConfigsManagementDBRepository)(nil).UpdateConfigByConfigName), ctx, obj)
}

// MockConfigsManagementCacheRepository is a mock of ConfigsManagementCacheRepository interface.
type MockConfigsManagementCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConfigsManagementCacheRepositoryMockRecorder
}

// MockConfigsManagementCacheRepositoryMockRecorder is the mock recorder for MockConfigsManagementCacheRepository.
type MockConfigsManagementCacheRepositoryMockRecorder struct {
	mock *MockConfigsManagementCacheRepository
}

// NewMockConfigsManagementCacheRepository creates a new mock instance.
func NewMockConfigsManagementCacheRepository(ctrl *gomock.Controller) *MockConfigsManagementCacheRepository {
	mock := &MockConfigsManagementCacheRepository{ctrl: ctrl}
	mock.recorder = &MockConfigsManagementCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigsManagementCacheRepository) EXPECT() *MockConfigsManagementCacheRepositoryMockRecorder {
	return m.recorder
}

// CreateConfigCache mocks base method.
func (m *MockConfigsManagementCacheRepository) CreateConfigCache(ctx context.Context, obj *entity.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConfigCache", ctx, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConfigCache indicates an expected call of CreateConfigCache.
func (mr *MockConfigsManagementCacheRepositoryMockRecorder) CreateConfigCache(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConfigCache", reflect.TypeOf((*MockConfigsManagementCacheRepository)(nil).CreateConfigCache), ctx, obj)
}

// DeleteConfigCache mocks base method.
func (m *MockConfigsManagementCacheRepository) DeleteConfigCache(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConfigCache", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConfigCache indicates an expected call of DeleteConfigCache.
func (mr *MockConfigsManagementCacheRepositoryMockRecorder) DeleteConfigCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConfigCache", reflect.TypeOf((*MockConfigsManagementCacheRepository)(nil).DeleteConfigCache), ctx, key)
}

// GetConfigCache mocks base method.
func (m *MockConfigsManagementCacheRepository) GetConfigCache(ctx context.Context, key string) (*entity.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigCache", ctx, key)
	ret0, _ := ret[0].(*entity.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigCache indicates an expected call of GetConfigCache.
func (mr *MockConfigsManagementCacheRepositoryMockRecorder) GetConfigCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigCache", reflect.TypeOf((*MockConfigsManagementCacheRepository)(nil).GetConfigCache), ctx, key)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(ctx context.Context, username string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), ctx, username)
}
