// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	auth "github.com/bobyindra/configs-management-service/module/configuration/internal/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockAuth) GenerateToken(param *auth.TokenParam, additionalClaim *auth.AdditionalClaim) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", param, additionalClaim)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthMockRecorder) GenerateToken(param, additionalClaim interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuth)(nil).GenerateToken), param, additionalClaim)
}

// ValidateClaim mocks base method.
func (m *MockAuth) ValidateClaim(ctx context.Context, r *http.Request) (*auth.ConfigsJWTClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateClaim", ctx, r)
	ret0, _ := ret[0].(*auth.ConfigsJWTClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateClaim indicates an expected call of ValidateClaim.
func (mr *MockAuthMockRecorder) ValidateClaim(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateClaim", reflect.TypeOf((*MockAuth)(nil).ValidateClaim), ctx, r)
}
